---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2022
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

clusters:
  nephio: 
    nodes: 1
    nodeSubnet: "172.88.0.0/16"
    podSubnet: "10.196.0.0/16"
    serviceSubnet: "10.96.0.0/16"
  regional:
    nodes: 1
    nodeSubnet: "172.89.0.0/16"
    podSubnet: "10.197.0.0/16"
    serviceSubnet: "10.97.0.0/16"
  edge-1:
    nodes: 1
    nodeSubnet: "172.90.0.0/16"
    podSubnet: "10.198.0.0/16"
    serviceSubnet: "10.98.0.0/16"
  edge-2:
    nodes: 1
    nodeSubnet: "172.91.0.0/16"
    podSubnet: "10.199.0.0/16"
    serviceSubnet: "10.99.0.0/16"
