---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2022
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################


apiVersion: infra.nephio.org/v1alpha1
kind: Cluster
metadata:
  name: regional
  labels:
    nephio.org/region: us-central1
    nephio.org/site-type: regional
    nephio.org/site: us-central1
repositoryRef:
  name: regional
---
apiVersion: infra.nephio.org/v1alpha1
kind: ClusterContext
metadata:
  name: regional
spec:
  siteCode: us-central1
  cniConfig:
    cniType: macvlan
    masterInterface: ens1
---
apiVersion: infra.nephio.org/v1alpha1
kind: ClusterScaleProfile
metadata:
  name: regional
spec:
  autoscaling: true
  nodeMax: 2400
  siteDensity: high
