---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2022
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

apiVersion: infra.nephio.org/v1alpha1
kind: Cluster
metadata:
  name: edge-2
  labels:
    nephio.org/region: us-central1
    nephio.org/site-type: edge
    nephio.org/site: edge-2
repositoryRef:
  name: edge-2
---
apiVersion: infra.nephio.org/v1alpha1
kind: ClusterContext
metadata:
  name: edge-2
spec:
  siteCode: edge-2
  cniConfig:
    cniType: macvlan
    masterInterface: ens1
---
apiVersion: infra.nephio.org/v1alpha1
kind: ClusterScaleProfile
metadata:
  name: edge-2
spec:
  autoscaling: false
  nodeMax: 12
  siteDensity: medium
