---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2022
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

apiVersion: nf.nephio.org/v1alpha1
kind: UPFClass
metadata:
  name: free5gc-upf
spec:
  packageRef:
    repository: free5gc-packages
    packageName: free5gc-upf
    revision: v1

  n3EndpointCount: 1
  n4EndpointCount: 1
  n6EndpointCount: 1
  n9EndpointCount: 0
