apiVersion: config.porch.kpt.dev/v1alpha1
kind: Repository
metadata:
  name: edge-1
  namespace: default
spec:
  content: Package
  deployment: true
  git:
    branch: main
    createBranch: true
    directory: /
    repo: http://gitea-server:3000/nephio-playground/participant-edge-1.git
    secretRef:
      name: gitea-personal-access-token
  type: git
