---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2022
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

apiVersion: config.porch.kpt.dev/v1alpha1
kind: Repository
metadata:
  name: regional
  namespace: default
spec:
  content: Package
  deployment: true
  git:
    branch: main
    createBranch: true
    directory: /
    repo: http://gitea-server:3000/nephio-playground/participant-regional.git
    secretRef:
      name: gitea-personal-access-token
  type: git
