---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2022
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

apiVersion: fn.kpt.dev/v1alpha1
kind: StarlarkRun
metadata:
  name: set-repos
  annotations:
    config.kubernetes.io/local-config: "true"
source: |
  # set the repo names
  def setrepo(resources, participant):
    for r in resources:
      # mutate the resource
      if r["kind"] == "Repository" and r["apiVersion"] == "config.porch.kpt.dev/v1alpha1" and "/participant-" in r["spec"]["git"]["repo"]:
        r["spec"]["git"]["repo"] = "http://gitea-server:3000/nephio-playground/" + participant + "-" + r["metadata"]["name"] + ".git"

  name = "participant"
  for r in ctx.resource_list["items"]:
    if r["kind"] == "ConfigMap" and r["metadata"]["name"] == "kptfile.kpt.dev":
      name = r["data"]["name"]

  setrepo(ctx.resource_list["items"], name)
