apiVersion: ipam.nephio.org/v1alpha1
kind: IPPrefix
metadata:
  name: sample-n3-net-prefix1
  labels:
    nephio.org/gateway: "true"
spec:
  kind: network
  prefix: 10.0.0.1/24
  network: sample-n3-net
  networkInstance: sample-vpc
