apiVersion: ipam.nephio.org/v1alpha1
kind: IPPrefix
metadata:
  name: aggregate0
  labels:
    nephio.org/network-name: ue-net
spec:
  kind: aggregate
  prefix: 10.0.0.0/8
  networkInstance: sample-vpc
