---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2022
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

name: Lint Code Base
# yamllint disable-line rule:truthy
on: [push, pull_request]

jobs:
  check-broken-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - name: Check broken links
        uses: gaurav-nelson/github-action-markdown-link-check@1.0.17
  check-super-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - name: Check super-linter
        uses: github/super-linter@v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_KUBERNETES_KUBEVAL: false
          KUBERNETES_KUBECONFORM_OPTIONS: '-ignore-missing-schemas'
          LINTER_RULES_PATH: /
  check-tox:
    name: Check syntax (tox)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - name: Install tox
        run: pip install tox
      - name: Check tox
        run: tox -e lint
