---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2021
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

name: Check End-to-End (On Demand)
# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - '**.go'
      - '**.sh'
      - '!.github/*'
  pull_request_review:
    types:
      - submitted

jobs:
  changes:
    runs-on: ubuntu-latest
    if: >-
      (
        github.event_name == 'pull_request_review' &&
        github.event.review.state == 'approved'
      ) ||
      github.event_name != 'pull_request_review'
    outputs:
      scripts: ${{ steps.filter.outputs.scripts }}
      golang: ${{ steps.filter.outputs.golang }}
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: dorny/paths-filter@v2.11.1
        if: ${{ !env.ACT }}
        id: filter
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: |
            scripts:
              - '**.sh'
            golang:
              - '**.go'
  check-scripts-format:
    name: Check scripts format
    if: needs.changes.outputs.scripts == 'true'
    needs: changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Run the sh-checker
        uses: luizm/action-sh-checker@v0.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHFMT_OPTS: -i 4 -s
        with:
          sh_checker_shellcheck_disable: true
  unit-test:
    name: Check Go lang unit tests
    if: needs.changes.outputs.golang == 'true'
    needs: changes
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-go@v3.4.0
        with:
          go-version: '^1.19'
      - uses: actions/cache@v3.0.11
        if: ${{ !env.ACT }}
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: GoTestTools/gotestfmt-action@v2.1.0
      - name: Run tests
        run: |
          set -euo pipefail
          go test -json -v ./... 2>&1 | tee /tmp/gotest.log | gotestfmt
      - name: Upload test log
        uses: actions/upload-artifact@v3.1.1
        if: ${{ !env.ACT }}
        with:
          name: test-log
          path: /tmp/gotest.log
          if-no-files-found: error
  functional-test:
    name: Check functional tests
    needs: check-scripts-format
    runs-on: ubuntu-20.04
    env:
      DEBUG: true
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Install dependencies
        working-directory: ./scripts
        run: ./install.sh
      - name: Configure infrastructure
        working-directory: ./scripts
        run: |
          [ -d "${KREW_ROOT:-$HOME/.krew}/bin" ] && export PATH="$PATH:${KREW_ROOT:-$HOME/.krew}/bin"
          ./configure.sh
      - name: Deploy Nephio services
        working-directory: ./scripts
        run: |
          [ -d "${KREW_ROOT:-$HOME/.krew}/bin" ] && export PATH="$PATH:${KREW_ROOT:-$HOME/.krew}/bin"
          ./deploy.sh
