---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2021
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

name: Check End-to-End (On Demand)
# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - '**.go'
      - '**.yml'
      - '**.sh'
      - '!.github/*'
  pull_request_review:
    types:
      - submitted

jobs:
  check-format:
    name: Check scripts format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run the sh-checker
        uses: luizm/action-sh-checker@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHFMT_OPTS: -i 4 -s
        with:
          sh_checker_shellcheck_disable: true
  system-test:
    name: Check system tests
    runs-on: ubuntu-20.04
    env:
      DEBUG: true
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: ./install.sh
      - name: Configure infrastructure
        run: ./configure.sh
      - name: Deploy Nephio services
        env:
          GITHUB_USERNAME: test
        run: ./deploy.sh
