---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2022
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

name: Scheduled Versions verification
# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  check-versions:
    permissions:
      contents: write  # for technote-space/create-pr-action to push code
      pull-requests: write  # for technote-space/create-pr-action to create a PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-go@v3.3.0
        with:
          go-version: '^1.19'
      - uses: technote-space/create-pr-action@v2.1.3
        with:
          EXECUTE_COMMANDS: |
            ./ci/update_versions.sh
          COMMIT_MESSAGE: 'Upgrade versions files'
          COMMIT_NAME: 'electrocucaracha bot'
          PR_BRANCH_NAME: "versions-update-${PR_ID}"
          PR_TITLE: 'chore: update versions'
  check-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: update Dockerfile
        uses: ludeeus/dockerfile-updater@21.01.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: 'chore: update Dockerfile'
